
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tictactoe
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-tictactoe
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-tictactoe
    spec:
      containers:
      - image: forsignup8580/tictactoe:v1
        imagePullPolicy: Always
        name: app-tictactoe
        ports:
        - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: service-tictactoe
spec:
  ports:
    - port: 80  
      targetPort: 8080  
  selector:
    app.kubernetes.io/name: app-tictactoe
